version: '3.16'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 537787
      POSTGRES_DB: aiodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  bot:
    image: "bot"
    depends_on:
      - db
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/app/bot"
    networks:
      - app-network
    volumes:
      - .:/app/bot
    command: "python3 -m bot"
    restart: always
    env_file: .env

    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"

networks:
  app-network:

volumes:
  postgres_data: